atCommand_src = WismoManager.c CommandManager.c CommandList.c simple_atoi.c \
command_NULL.c \
command_AT.c \
command_CPIN.c \
command_CSQ.c \
command_CSMS.c \
command_CPMS.c \
command_CMGF.c \
command_CSCA.c \
command_CSCB.c \
command_CSMP.c \
command_CNMI.c \
command_CMGL.c \
command_CMGS.c \
command_CMGR.c \
command_CMGD.c \
command_EREPP.c